Repository node-saml/xml-crypto, pull requests merged in 2023-10, with the labels that each got.

#394 Reduce public interface by making some methods private
  src/signed-xml.ts
  src/types.ts
Labels: chore, breaking-change

#395 Make references accessible only via get/set
  README.md
  src/signed-xml.ts
  test/signature-unit-tests.spec.ts
Labels: breaking-change

#396 Move validation messages to each reference
  README.md
  src/signed-xml.ts
  src/types.ts
  test/hmac-tests.spec.ts
  test/saml-response-tests.spec.ts
Labels: breaking-change

#397 Improve code clarity; remove unused functions
  src/signed-xml.ts
  test/document-tests.spec.ts
Labels: chore, breaking-change

#389 Add support for directly querying a node to see if it has passed validation
  README.md
  src/signed-xml.ts
  src/types.ts
  test/document-tests.spec.ts
Labels: enhancement

#377 Ensure the X509Certificate tag is properly prefixed
  src/signed-xml.ts
  test/signature-unit-tests.spec.ts
Labels: bug

#402 Update dependencies
  package-lock.json
  package.json
  src/c14n-canonicalization.ts
  src/enveloped-signature.ts
  src/exclusive-canonicalization.ts
  src/signed-xml.ts
  src/utils.ts
  test/c14n-non-exclusive-unit-tests.spec.ts
  test/c14nWithComments-unit-tests.spec.ts
  test/canonicalization-unit-tests.spec.ts
  test/document-tests.spec.ts
  test/hmac-tests.spec.ts
  test/key-info-tests.spec.ts
  test/saml-response-tests.spec.ts
  test/signature-integration-tests.spec.ts
  test/signature-unit-tests.spec.ts
  test/wsfed-metadata-tests.spec.ts
Labels: dependencies

#406 Remove default for digest algorithm
  README.md
  src/signed-xml.ts
  test/hmac-tests.spec.ts
  test/key-info-tests.spec.ts
  test/signature-integration-tests.spec.ts
  test/signature-unit-tests.spec.ts
Labels: breaking-change
