Repository node-saml/xml-crypto, pull requests merged in 2023-07, with the labels that each got.

#330 fix issue in case when namespace has no prefix
  .gitignore
  lib/c14n-canonicalization.js
  lib/utils.js
  test/c14n-non-exclusive-unit-test.js
Labels: bug

#335 Exports C14nCanonicalization, ExclusiveCanonicalization
  index.js
Labels: enhancement

#336 Exports C14nCanonicalization, ExclusiveCanonicalization
  index.js
Labels: enhancement

#337 Fix missing `index.js` on release
  package.json
Labels: bug

#338 Fix test case error
  test/c14n-non-exclusive-unit-test.js
Labels: bug

#339 Update gren for better support for branches
  package-lock.json
  package.json
Labels: dependencies

#341 Don't force `master` branch when generating changelog
  package.json
Labels: chore

#340 Update gren for better support for branches
  package-lock.json
  package.json
Labels: dependencies

#342 Don't force `master` branch when generating changelog
  package.json
Labels: chore

#343 Rename files in preparation for TS migration
  .eslintrc.json
  .github/workflows/ci.yml
  .gitignore
  .mocharc.json
  .nycrc.json
  .prettierignore
  README.md
  index.d.ts
  package-lock.json
  package.json
  src/c14n-canonicalization.ts
  src/enveloped-signature.ts
  src/exclusive-canonicalization.ts
  src/hash-algorithms.ts
  src/index.ts
  src/signature-algorithms.ts
  src/signed-xml.ts
  src/types.ts
  src/utils.ts
  test/c14n-non-exclusive-unit-tests.spec.ts
  test/c14nWithComments-unit-tests.spec.ts
  test/canonicalization-unit-tests.spec.ts
  test/document-tests.spec.ts
  test/hmac-tests.spec.ts
  test/key-info-tests.spec.ts
  test/saml-response-tests.spec.ts
  test/signature-integration-tests.spec.ts
  test/signature-unit-tests.spec.ts
  test/utils-tests.spec.ts
  test/wsfed-metadata-tests.spec.ts
  tsconfig.eslint.json
  tsconfig.json
Labels: chore

#325 Convert this project to TypeScript
  src/c14n-canonicalization.ts
  src/enveloped-signature.ts
  src/exclusive-canonicalization.ts
  src/hash-algorithms.ts
  src/index.ts
  src/signature-algorithms.ts
  src/signed-xml.ts
  src/utils.ts
  test/c14n-non-exclusive-unit-tests.spec.ts
  test/c14nWithComments-unit-tests.spec.ts
  test/canonicalization-unit-tests.spec.ts
  test/document-tests.spec.ts
  test/hmac-tests.spec.ts
  test/key-info-tests.spec.ts
  test/saml-response-tests.spec.ts
  test/signature-integration-tests.spec.ts
  test/signature-unit-tests.spec.ts
  test/utils-tests.spec.ts
  test/wsfed-metadata-tests.spec.ts
Labels: chore

#345 Enforce eslint `no-this-alias`
  .eslintrc.json
  src/signed-xml.ts
Labels: chore

#346 Enforce eslint `prefer-template`
  .eslintrc.json
  src/c14n-canonicalization.ts
  src/exclusive-canonicalization.ts
  src/signed-xml.ts
  test/signature-unit-tests.spec.ts
  test/utils-tests.spec.ts
Labels: chore

#347 Enforce eslint `deprecation`
  .eslintrc.json
Labels: chore

#349 Enforce eslint `no-unused-vars`
  .eslintrc.json
  src/signed-xml.ts
  test/key-info-tests.spec.ts
Labels: chore

#363 Rename `findChilds()` to `findChildren()`
  src/exclusive-canonicalization.ts
  src/signed-xml.ts
  src/utils.ts
Labels: chore

#364 Fix `pemToDer()` return type
  src/signed-xml.ts
  src/utils.ts
  test/static/client_public.der
  test/utils-tests.spec.ts
Labels: bug, breaking-change

#369 Add type checking
  src/c14n-canonicalization.ts
  src/signed-xml.ts
  src/utils.ts
  test/c14nWithComments-unit-tests.spec.ts
  test/canonicalization-unit-tests.spec.ts
  test/key-info-tests.spec.ts
  test/signature-unit-tests.spec.ts
  test/static/valid_signature_with_root_level_sig_namespace.xml
  tsconfig.json
Labels: chore
