Repository node-saml/xml-crypto, pull requests merged in 2024-01, with the labels that each got.

#439 Enhance derToPem to support XML pretty-print
  src/signed-xml.ts
  src/utils.ts
  test/static/keyinfo - pretty-printed.xml
  test/static/keyinfo.pem
  test/utils-tests.spec.ts
Labels: enhancement

#432 Chore: Update README.md
  README.md
Labels: documentation

#445 Set `getCertFromKeyInfo` to `noop`
  src/signed-xml.ts
  test/document-tests.spec.ts
  test/key-info-tests.spec.ts
  test/signature-unit-tests.spec.ts
Labels: breaking-change
